version: '3.3'

services:
   freterentjesidio:
     depends_on:
       - dbfreterent  
     image: freterentjesidio:latest
     ports:
       - "8080:8080"
     restart: always
     environment:
       - SPRING_PROFILES_ACTIVE=prod
       - DSI2019_DB_HOST=jdbc:sqlserver://localhost;databaseName=FreteRent
       - DSI2019_DB_USERNAME=bob
       - DSI2019_DB_PASSWORD=bob
   dbfreterent:
     image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
     restart: always
#     ports:
#       - "3306:3306"
     environment:
       ACCEPT_EULA=Y
       SA_PASSWORD=bob